- name: Configure httpd with certificates
  become: yes
  become_method: doas
  template:
    src: httpd.conf.j2
    dest: /etc/httpd.conf

- name: Check httpd configuration
  become: yes
  become_method: doas
  shell:
    cmd: httpd -n

- name: Start httpd server
  become: yes
  become_method: doas
  shell:
    cmd: rcctl restart httpd
